<template>
  <div class="section-details">
    <h2 class="section-heading">
      <span>Projects</span>
    </h2>
    <ProjectDescription :data="brainingCamp" />
    <ProjectDescription :data="orderManagementSystem" />
  </div>
</template>
<script>
import ProjectDescription from "../components/ProjectDescription.vue";

export default {
  name: "Projects",
  components: {
    ProjectDescription,
  },
  data() {
    return {
      brainingCamp: {
        name: "Brainingcamp",
        domain: "Online Education",
        description: [
          "Brainingcamp is an application for teaching and learning maths in a visual and dynamic way. It allows teachers to give work to the students and students can submit their work to the teachers by sharing the code/link generated by the application.",
        ],
        technologies: ["Create.js", "Node.js", "Express.js", "Vue.js"],
        image: {
          img: "brainingcamp.gif",
          placeholder: "brainingcamp-placeholder.jpg",
        },
      },
      orderManagementSystem: {
        name: "Order Management System",
        domain: "E commerce",
        description: [
          "Project involved the development of a system that helps the sales and presales team to create the quote based on the client requirement, calculate cost for implementing a lighting solution and upon finalization of the quote PO is generated and processed. An order can be tracked and processed by releases.",
        ],
        technologies: ["C#", "MS SQL Serve"],
      },
    };
  },
};
</script>
<style scoped>
</style>